[tool.poetry]
name = "telegram_data_agent"
version = "0.1.0"
description = "SQL agent using agents to query telegram data"
authors = ["Your Name"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
zenml = "0.56.1"
pandas = "^2.1.0"
pydantic-settings = "^2.0.0"

[tool.poe.tasks]
run-telegram-etl = "python -m tools.run --run-etl"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"